import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-slate-50 text-slate-900">
        <div className="flex min-h-screen">
          <SideBar />
          <div className="flex-1 overflow-y-auto">
            <Header />
            <main className="p-6 lg:p-10">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}

function SideBar() {
  return (
    <aside className="group flex w-20 flex-col bg-slate-900 text-slate-100 transition-all duration-300 hover:w-64">
      <div className="flex h-16 items-center justify-center border-b border-slate-800">
        <span className="text-lg font-semibold tracking-wide">You&AI</span>
      </div>
      <nav className="flex-1 space-y-1 p-3">
        <NavItem href="/" label="Home" />
        <NavItem href="#contact" label="Contact Us" />
      </nav>
      <div className="p-3 text-xs text-slate-400">© {new Date().getFullYear()} You&AI</div>
    </aside>
  );
}

function NavItem({ href, label }: { href: string; label: string }) {
  return (
    <a
      href={href}
      className="flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-slate-800 hover:text-white"
    >
      <span className="flex h-8 w-8 items-center justify-center rounded bg-slate-800 text-xs uppercase text-slate-300">
        {label.slice(0, 2)}
      </span>
      <span className="opacity-0 transition-opacity duration-300 group-hover:opacity-100">
        {label}
      </span>
    </a>
  );
}

function Header() {
  return (
    <header className="flex items-center justify-between border-b border-slate-200 bg-white/80 px-6 py-4 backdrop-blur">
      <h1 className="text-xl font-semibold text-slate-800">Dashboard</h1>
      <button className="rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700">
        New Project
      </button>
    </header>
  );
}
